Repository GeneriedJenelle/The-World-Server-Redux, pull requests merged in 2019-02, with the labels that each got.

#190 Stops dead, stunned or lying-down people from driving cars
  code/modules/vehicles/car/car_datum.dm
Labels: in progress

#194 Map Updates for Psychiatry/Medical, and various tweaks
  maps/Geminus/geminus-1.dmm
  maps/Geminus/geminus-2.dmm
  maps/Geminus/geminus_areas.dm
  maps/Geminus/geminus_elevator.dm
Labels: in progress

#195 Increases the amount of psych slots and adds new alt titles
  code/game/jobs/job/medical.dm
Labels: in progress

#196 Quick recharger re-adjustment
  code/game/machinery/recharger.dm
Labels: in progress

#207 New sound effects for punching, ambience, and voting
  sound/ambience/alarm4.ogg
  sound/ambience/ambisin1.ogg
  sound/ambience/shipambience.ogg
  sound/weapons/punch1.ogg
  sound/weapons/punch2.ogg
  sound/weapons/punch3.ogg
  sound/weapons/punch4.ogg
Labels: in progress

#206 Changes up a few gamemodes
  code/game/gamemodes/heist/heist.dm
  code/game/gamemodes/mixed/conflux.dm
  code/game/gamemodes/mixed/infestation.dm
  code/game/gamemodes/mixed/lizard.dm
  code/game/gamemodes/mixed/traitorling.dm
  code/game/gamemodes/mixed/uprising.dm
  code/game/gamemodes/mixed/visitors.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/technomancer/technomancer.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: in progress, requested

#201 Some spiders are super tanky
  code/modules/mob/living/simple_animal/animals/giant_spider.dm
Labels: NERF THIS REEE

#209 Sofas buckle in the right direction depending on dir
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: bug squash, in progress

#211 Adds SOP Law books & Updates Library Icons
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/weapons/manuals.dm
  icons/obj/library.dmi
Labels: in progress

#214 Fixes Crew Monitoring (Suit Sensors) Computer
  code/datums/repositories/crew.dm
  code/datums/repositories/crew/_defines.dm
  code/datums/repositories/crew/binary.dm
  code/datums/repositories/crew/crew.dm
  code/datums/repositories/crew/crew_sensor_modifier.dm
  code/datums/repositories/crew/general.dm
  code/datums/repositories/crew/tracking.dm
  code/datums/repositories/crew/vital.dm
  code/datums/repositories/crew/~defines.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  nano/templates/crew_monitor.tmpl
  nano/templates/crew_monitor_map_content.tmpl
  nano/templates/crew_monitor_map_header.tmpl
  polaris.dme
Labels: DO NOT MERGE, bug squash, in progress

#213 Adds microphones from goon (with modifications)
  SQL/feedback_schema.sql
  code/game/objects/items/devices/microphones.dm
  icons/obj/radio.dmi
  icons/obj/structures.dmi
  icons/obj/vending.dmi
  icons/turf/walls.dmi
  maps/Geminus/geminus-1.dmm
  maps/Geminus/geminus-2.dmm
  maps/Geminus/geminus-3.dmm
  polaris.dme
  sound/items/mic_feedback.ogg
Labels: in progress, new feature

#215 Prevents people from joining with the same name
  code/modules/mob/new_player/new_player.dm
Labels: in progress

#219 Adds Word Processor Program - Baystation Port
  code/__defines/misc.dm
  code/_helpers/text.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
  nano/templates/word_processor.tmpl
  polaris.dme
Labels: in progress, new feature

#218 Ports Digital Warrants from Bay
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/devices/holowarrant.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/modular_computers/file_system/programs/police/digitalwarrant.dm
  html/changelogs/Nero-07-DigitalWarrant.yml
  icons/obj/device.dmi
  maps/Geminus/geminus-2.dmm
  nano/templates/digitalwarrant.tmpl
  polaris.dme
Labels: in progress, new feature

#225 Updates Modular Computer Icons
  code/__defines/misc.dm
  icons/obj/modular_components.dmi
  icons/obj/modular_console.dmi
Labels: in progress

#212 Internships and job tweaks
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/science.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/modular_computers/file_system/programs/card.dm
Labels: in progress

#216 (Should) Fix Matchmatching
  code/modules/mob/new_player/new_player.dm
Labels: in progress

#232 Upgrades Thug Mode
  code/game/antagonist/station/thug.dm
Labels: in progress

#233 Fixes gang name display for thugs
  code/game/antagonist/station/thug.dm
  code/game/gamemodes/thug/thug.dm
Labels: in progress

#234 Changes thalers to credits in more instances
  code/modules/economy/cash_register.dm
  code/modules/economy/price_list.dm
  code/modules/economy/retail_scanner.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: in progress

#236 Adds more nicotene to cigarettes
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: in progress

#243 Adds Emotes to OOC.
  code/controllers/configuration.dm
  code/game/verbs/ooc.dm
  code/modules/emoji/emoji_parse.dm
  config/example/config.txt
  html/changelogs/JJRcop-OOCemoji.yml
  icons/emoji.dmi
  polaris.dme
Labels: in progress

#244 Adds round logs & individual dialogue verbs for moderation
  code/_helpers/mobs.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin_attack_log.dm
  code/modules/admin/admin_tools.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets/admin_secrets/admin_logs.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/say.dm
Labels: in progress

#245 Makes space bears into brown bears + Adds more emojis + Updates IV drip
  code/modules/mob/living/simple_animal/animals/bear.dm
  icons/emoji.dmi
  icons/obj/iv_drip.dmi
Labels: in progress

#247 Reduces CMO age requirements
  code/game/jobs/job/medical.dm
Labels: in progress

#248 Reduces CMO min age (I rubbed my eyes version)
  code/game/jobs/job/medical.dm
Labels: in progress

#251 Makes Crickets Quieter.
  code/game/jobs/job/medical.dm
  sound/ambience/shipambience.ogg
Labels: in progress

#253 Fixes Body Cameras, Reduces Coal Amounts
  code/modules/mining/ore_datum.dm
Labels: in progress

#249 fixes car move delay bug
  code/modules/vehicles/car/car.dm
Labels: Review!, bounty $$, bug squash, good first issue, in progress

#250 Fixes the hand-tele (from what I can tell)
  code/game/objects/items/weapons/teleportation.dm
Labels: Review!, bounty $$, bug squash, good first issue, in progress
